import type { Metadata } from "next";
import AnimatedBackground from "./components/animatedBackground";
import DropdownMenu from "./components/dropdownMenu";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased bg-white relative overflow-hidden">
        <AnimatedBackground />
        <div className="relative z-10">
          <DropdownMenu />
          {children}
        </div>
        {/* </div> */}
      </body>
    </html>
  );
}
