import type { Metadata } from "next";
import AnimatedBackground from "../components/animatedBackground";
import DropdownMenu from "../components/dropdownMenu";
import LanguageSwitcher from "../components/languageSwitcher";
import "../globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children, params }: Readonly<{ children: React.ReactNode, params?: any }>) {

  return (
    <html lang="en">
      <body className="antialiased bg-white relative overflow-hidden">
        <AnimatedBackground />
        <div className="relative z-10">
          <DropdownMenu />
          <LanguageSwitcher />
          {children}
        </div>
        {/* </div> */}
      </body>
    </html>
  );
}
